import { describe, expect, it } from 'vitest';
import { LocalAdaptiveEngine } from '../src/domain/adaptive/fallback';
import { OnDeviceMLAdaptiveEngine, buildAdaptiveFeatures } from '../src/domain/adaptive/onDeviceModel';
const context = { gameKey: 'memory-match' as const, currentDifficulty: 'medium' as const, recentResults: [{ accuracy: 0.95, attempts: 1, durationMs: 20000, completed: true, difficulty: 'medium' as const }, { accuracy: 0.9, attempts: 1, durationMs: 21000, completed: true, difficulty: 'medium' as const }], consecutiveSuccesses: 2, consecutiveFailures: 0 };
const distance = (a: string, b: string) => Math.abs(['easy', 'medium', 'hard'].indexOf(a) - ['easy', 'medium', 'hard'].indexOf(b));
describe('adaptive engines', () => {
  it('normalizes declared duration and attempts ranges', () => { const values = buildAdaptiveFeatures(context, 'medium', { durationMs: { min: 0, max: 120000 }, attempts: { min: 0, max: 10 } }); expect(values).toHaveLength(10); expect(values[1]).toBeGreaterThan(0.8); expect(values[2]).toBeGreaterThan(0.8); });
  it('runs logistic inference or a safe offline fallback', () => { const result = new OnDeviceMLAdaptiveEngine().recommendNextDifficulty(context); expect(['on-device-ml', 'rules-fallback']).toContain(result.engine); expect(result.confidence).toBeGreaterThan(0); expect(result.featureSchemaVersion).toBe('adaptive-features-v1'); expect(distance(result.difficulty, 'medium')).toBeLessThanOrEqual(1); });
  it('falls back for invalid and unsupported model artifacts', () => { const invalid = new OnDeviceMLAdaptiveEngine({ modelVersion: 'bad', schemaVersion: 'old', bias: 0, weights: [] }); const result = invalid.recommendNextDifficulty(context); expect(result.engine).toBe('rules-fallback'); expect(result.fallbackReason).toMatch(/model schema|invalid/); });
  it('falls back when required activity features are missing', () => { const missing = { ...context, recentResults: [{ ...context.recentResults[0], accuracy: Number.NaN }] }; const result = new OnDeviceMLAdaptiveEngine().recommendNextDifficulty(missing); expect(result.engine).toBe('rules-fallback'); expect(result.fallbackReason).toContain('missing'); });
  it('falls back when confidence or history is insufficient', () => { const result = new OnDeviceMLAdaptiveEngine().recommendNextDifficulty({ ...context, recentResults: [] }); expect(result.engine).toBe('rules-fallback'); expect(result.fallbackReason).toContain('confidence'); });
  it('keeps deterministic fallback within one tier and explains the choice', () => { const result = new LocalAdaptiveEngine().recommendNextDifficulty(context); expect(result.engine).toBe('rules-fallback'); expect(distance(result.difficulty, 'medium')).toBeLessThanOrEqual(1); expect(result.rationale.length).toBeGreaterThan(10); });
  it('does not increase difficulty after repeated failures at the hard boundary', () => { const result = new LocalAdaptiveEngine().recommendNextDifficulty({ ...context, currentDifficulty: 'hard', recentResults: [{ accuracy: 0.2, attempts: 8, durationMs: 120000, completed: false, difficulty: 'hard' }], consecutiveSuccesses: 0, consecutiveFailures: 3 }); expect(result.difficulty).toBe('medium'); });
});
