import NetInfo from '@react-native-community/netinfo';
import { getDatabase } from '../../data/local/database';
import { supabase } from '../auth/supabase';
const client = supabase as any;
let flushing = false;
async function currentPatientId() { const { data: session } = await client.auth.getSession(); const authUserId = session.session?.user.id; if (!authUserId) throw new Error('session unavailable'); const { data: profile } = await client.from('profiles').select('id').eq('auth_user_id', authUserId).maybeSingle(); const { data: patient } = await client.from('patients').select('id').eq('profile_id', profile?.id).maybeSingle(); if (!patient) throw new Error('patient unavailable'); return patient.id; }
export async function flushOutbox() {
  if (flushing) return; flushing = true;
  try { const db = await getDatabase(); const pending = await db.getAllAsync<{ id: string; entity_type: string; payload_json: string }>("SELECT id, entity_type, payload_json FROM sync_outbox WHERE state = 'pending' AND next_attempt_at <= datetime('now') ORDER BY next_attempt_at LIMIT 25");
    for (const item of pending) { try { const payload = JSON.parse(item.payload_json);
      if (item.entity_type === 'game_result') { const patientId = await currentPatientId(); const { data: game } = await client.from('games').select('id').eq('game_key', payload.gameKey).maybeSingle(); if (!game) throw new Error('game unavailable'); const { error: sessionError } = await client.from('game_sessions').upsert({ id: payload.sessionId, client_event_id: payload.clientEventId, patient_id: patientId, game_id: game.id, status: 'completed', started_at: payload.createdAt, completed_at: payload.createdAt, client_created_at: payload.createdAt, metadata: payload.metrics }, { onConflict: 'client_event_id' }); if (sessionError) throw sessionError; const { error: resultError } = await client.from('game_results').upsert({ game_session_id: payload.sessionId, source: 'client', observed_at: payload.createdAt, score: payload.score, max_score: payload.maxScore, accuracy: payload.accuracy, response_time_ms: payload.durationMs, attempts_count: payload.attempts, parameters: payload.metrics }, { onConflict: 'game_session_id' }); if (resultError) throw resultError; await db.runAsync("UPDATE local_game_results SET sync_state = 'synced' WHERE session_id = ?", payload.sessionId); }
      if (item.entity_type === 'reminder_event') { const patientId = await currentPatientId(); const { error } = await client.from('reminder_events').upsert({ id: payload.clientEventId, client_event_id: payload.clientEventId, reminder_id: payload.reminderId, patient_id: patientId, scheduled_for: payload.scheduledFor, status: payload.status, delivered_at: payload.completedAt, client_created_at: payload.completedAt, metadata: { source: 'patient-mobile' } }, { onConflict: 'client_event_id' }); if (error) throw error; await db.runAsync("UPDATE local_reminder_events SET sync_state = 'synced' WHERE client_event_id = ?", payload.clientEventId); await db.runAsync("UPDATE local_reminders SET sync_state = 'synced' WHERE id = ?", payload.reminderId); }
      await db.runAsync("UPDATE sync_outbox SET state = 'synced', attempts = attempts + 1, last_error = NULL WHERE id = ?", item.id);
    } catch (error) { await db.runAsync("UPDATE sync_outbox SET attempts = attempts + 1, last_error = ?, next_attempt_at = datetime('now', '+' || min(60, max(5, attempts * 5)) || ' minutes') WHERE id = ?", error instanceof Error ? error.message.slice(0, 200) : 'sync failed', item.id); } }
  } finally { flushing = false; }
}
export function startSyncMonitor() { return NetInfo.addEventListener((state) => { if (state.isConnected && state.isInternetReachable !== false) void flushOutbox(); }); }
