import { Link } from 'expo-router';
import { useEffect, useState } from 'react';
import { SafeAreaView, ScrollView, Text } from 'react-native';
import { Card, Button, Heading, OfflineBanner, StatusPill } from '../../src/components/ui';
import { colors, GAME_KEYS, gameLabels, spacing, styles } from '../../src/theme/tokens';
import { listGameResults, listReminders } from '../../src/data/local/repositories';
import type { GameResult, Reminder } from '../../src/types';
import { useAuth } from '../_layout';
export default function Home() { const { profile } = useAuth(); const [reminders, setReminders] = useState<Reminder[]>([]); const [results, setResults] = useState<GameResult[]>([]); useEffect(() => { let active = true; Promise.all([listReminders(), listGameResults()]).then(([nextReminders, nextResults]) => { if (active) { setReminders(nextReminders); setResults(nextResults); } }); return () => { active = false; }; }, []); const nextReminder = reminders.find((item) => !item.completedToday) ?? reminders[0]; const completedKeys = new Set(results.filter((item) => item.completed && new Date(item.createdAt).toDateString() === new Date().toDateString()).map((item) => item.gameKey)); return <SafeAreaView style={styles.screen}><ScrollView contentContainerStyle={styles.content}><Heading subtitle="A gentle day starts here.">Hello, {profile?.displayName?.split(' ')[0] ?? 'friend'}</Heading><OfflineBanner /><Card style={{ backgroundColor: colors.greenTint }}><StatusPill>Next reminder</StatusPill>{nextReminder ? <><Text style={{ fontSize: 22, fontWeight: '800', color: colors.greenDark }}>{nextReminder.title}</Text><Text style={{ color: colors.muted }}>{nextReminder.message}</Text><Text style={{ color: colors.greenDark, fontWeight: '700' }}>{nextReminder.completedToday ? 'Done today' : 'Ready when you are'}</Text></> : <Text style={{ color: colors.muted }}>You have a calm day ahead.</Text>}<Link href="/(tabs)/reminders" asChild><Button title="See reminders" variant="secondary" /></Link></Card><Card><StatusPill>Today</StatusPill>{GAME_KEYS.map((key) => <Text key={key} style={{ color: colors.ink, fontSize: 17 }}>{gameLabels[key].icon}  {gameLabels[key].title} — {completedKeys.has(key) ? 'Completed' : 'Not started'}</Text>)}<Link href="/(tabs)/games" asChild><Button title="Play a game" /></Link></Card><Card style={{ backgroundColor: colors.brownTint }}><Text style={{ fontSize: 20, fontWeight: '800', color: colors.ink }}>Need a little help?</Text><Text style={{ color: colors.muted }}>You can read the help guide or ask your care team.</Text><Link href="/help" asChild><Button title="Open help" variant="secondary" /></Link></Card><Text style={{ color: colors.muted, textAlign: 'center', marginTop: spacing.md }}>Your activities are for enjoyment and connection, not a medical test.</Text></ScrollView></SafeAreaView>; }
