/* eslint-disable react-hooks/purity */
import { useLocalSearchParams, useRouter } from 'expo-router';
import { useMemo, useState } from 'react';
import { Pressable, SafeAreaView, ScrollView, Text, View } from 'react-native';
import { Button, Card, Heading, StatusPill } from '../../src/components/ui';
import { gameLabels, colors, styles, spacing, type GameKey } from '../../src/theme/tokens';
import { OnDeviceMLAdaptiveEngine } from '../../src/domain/adaptive/onDeviceModel';
import { saveGameResult } from '../../src/data/local/repositories';
import type { AdaptiveContext } from '../../src/domain/adaptive/types';
const engine = new OnDeviceMLAdaptiveEngine();
const objects = ['🍵', '🪔', '🌼', '🧺', '☂️', '🍋', '🎋', '🍚'];
export default function GameScreen() { const router = useRouter(); const { gameKey } = useLocalSearchParams<{ gameKey: GameKey }>(); const key = (gameKey ?? 'memory-match') as GameKey; const game = gameLabels[key]; const [started, setStarted] = useState(false); const [step, setStep] = useState(0); const [score, setScore] = useState(0); const [selected, setSelected] = useState<number[]>([]); const [finished, setFinished] = useState(false); const [recommendation, setRecommendation] = useState<string>(''); const content = useMemo(() => key === 'memory-match' ? ['🍵','🪔','🍵','🪔'] : objects, [key]);
  function finish(finalScore = score) { const results = [{ accuracy: finalScore / (key === 'pattern-sequence' ? 5 : key === 'memory-match' ? 2 : 3), attempts: Math.max(1, step + 1), durationMs: 30000, completed: true, difficulty: 'easy' as const }]; const context: AdaptiveContext = { gameKey: key, currentDifficulty: 'easy', recentResults: results, consecutiveSuccesses: finalScore > 0 ? 1 : 0, consecutiveFailures: finalScore === 0 ? 1 : 0 }; const next = engine.recommendNextDifficulty(context); setRecommendation(`${next.rationale} (${next.engine === 'on-device-ml' ? 'offline ML' : 'gentle fallback'})`); saveGameResult({ gameKey: key, sessionId: `local_${Date.now()}`, clientEventId: `event_${Date.now()}`, difficulty: 'easy', score: finalScore, maxScore: key === 'pattern-sequence' ? 5 : key === 'memory-match' ? 2 : 3, accuracy: results[0].accuracy, attempts: results[0].attempts, durationMs: results[0].durationMs, completed: true, metrics: { engine: next.engine, engineVersion: next.engineVersion, recommendationId: next.recommendationId }, createdAt: new Date().toISOString(), syncState: 'queued' }); setFinished(true); }
  function choose(index: number) { if (key === 'memory-match') { const next = [...selected, index]; setSelected(next); if (next.length === 2) { const pair = next.map((i) => content[i]).join(''); if (pair === '🍵🍵' || pair === '🪔🪔') setScore((value) => value + 1); setSelected([]); setStep((value) => value + 1); if (step >= 1) finish(score + (pair === '🍵🍵' || pair === '🪔🪔' ? 1 : 0)); } } else { setScore((value) => value + (index === 0 ? 1 : 0)); setStep((value) => value + 1); if (step >= (key === 'pattern-sequence' ? 4 : 2)) finish(score + (index === 0 ? 1 : 0)); } }
  if (finished) return <SafeAreaView style={styles.screen}><ScrollView contentContainerStyle={styles.content}><Heading subtitle="You took your time and finished the activity.">Well done</Heading><Card style={{ backgroundColor: colors.greenTint }}><Text style={{ fontSize: 44 }}>🌿</Text><Text style={{ fontSize: 22, fontWeight: '800', color: colors.greenDark }}>Your activity was saved</Text><Text style={{ color: colors.muted }}>It will sync when you are connected. This is not a medical score.</Text></Card><Card><StatusPill>Personal pace</StatusPill><Text style={{ color: colors.ink, lineHeight: 24 }}>{recommendation}</Text></Card><Button title="Back to games" onPress={() => router.replace('/(tabs)/games')} /></ScrollView></SafeAreaView>;
  return <SafeAreaView style={styles.screen}><ScrollView contentContainerStyle={styles.content}><Heading subtitle={game.subtitle}>{game.title}</Heading>{!started ? <><Card><Text style={{ fontSize: 52 }}>{game.icon}</Text><Text style={{ color: colors.muted, lineHeight: 24 }}>There is no timer. Look, think, and tap when you are ready. You can pause at any time.</Text></Card><Button title="Start gently" onPress={() => setStarted(true)} /><Button title="Go back" variant="quiet" onPress={() => router.back()} /></> : <><StatusPill>Round {Math.min(step + 1, key === 'pattern-sequence' ? 5 : key === 'memory-match' ? 2 : 3)}</StatusPill><Card><Text style={{ textAlign: 'center', fontSize: 20, fontWeight: '800' }}>{key === 'memory-match' ? 'Find the two matching pairs' : key === 'object-recall' ? 'Choose the familiar objects' : 'What comes next in the pattern?'}</Text><View style={{ flexDirection: 'row', flexWrap: 'wrap', gap: spacing.sm, justifyContent: 'center', marginTop: spacing.md }}>{(key === 'memory-match' ? content : key === 'object-recall' ? content : ['🌼','🌿','🌼','🌿']).map((item, index) => <Pressable key={`${item}-${index}`} accessibilityRole="button" accessibilityLabel={`Option ${index + 1}`} onPress={() => choose(index)} style={{ width: 70, height: 70, borderRadius: 16, backgroundColor: selected.includes(index) ? colors.greenTint : colors.brownTint, alignItems: 'center', justifyContent: 'center' }}><Text style={{ fontSize: 34 }}>{item}</Text></Pressable>)}</View></Card><Button title="Pause" variant="quiet" onPress={() => setStarted(false)} /></>}</ScrollView></SafeAreaView>; }
