import React from 'react';
import { ActivityIndicator, Pressable, StyleSheet, Text, TextInput, View, type PressableProps } from 'react-native';
import { colors, defaultTheme, radii, shadow, spacing, typography } from '../../theme/tokens';
export function Card({ children, style }: { children: React.ReactNode; style?: object }) { return <View style={[styles.card, style]}>{children}</View>; }
export function Button({ title, onPress, variant = 'primary', disabled }: { title: string; onPress?: PressableProps['onPress']; variant?: 'primary'|'secondary'|'quiet'|'danger'; disabled?: boolean }) { return <Pressable accessibilityRole="button" accessibilityLabel={title} disabled={disabled} onPress={onPress} style={({ pressed }) => [styles.button, variant === 'secondary' && styles.secondary, variant === 'quiet' && styles.quiet, variant === 'danger' && styles.danger, pressed && styles.pressed, disabled && styles.disabled]}><Text style={[styles.buttonText, variant !== 'primary' && styles.darkButtonText]}>{title}</Text></Pressable>; }
export function Heading({ children, subtitle }: { children: React.ReactNode; subtitle?: string }) { return <View style={styles.heading}><Text accessibilityRole="header" style={styles.title}>{children}</Text>{subtitle ? <Text style={styles.subtitle}>{subtitle}</Text> : null}</View>; }
export function StatusPill({ children, tone = 'green' }: { children: React.ReactNode; tone?: 'green'|'coral'|'brown' }) { return <View style={[styles.pill, { backgroundColor: tone === 'green' ? colors.greenTint : tone === 'coral' ? colors.coralTint : colors.brownTint }]}><Text style={styles.pillText}>{children}</Text></View>; }
export function OfflineBanner() { return <View style={styles.offline}><Text style={styles.offlineText}>✓ Saved safely on this device</Text></View>; }
export function Field({ label, value, onChangeText, placeholder, multiline }: { label: string; value: string; onChangeText: (value: string) => void; placeholder?: string; multiline?: boolean }) { return <View style={{ gap: 6 }}><Text style={styles.label}>{label}</Text><TextInput accessibilityLabel={label} value={value} onChangeText={onChangeText} placeholder={placeholder} placeholderTextColor={colors.muted} multiline={multiline} style={[styles.field, multiline && { minHeight: 100, textAlignVertical: 'top' }]} /></View>; }
export function Loading() { return <View style={styles.loading}><ActivityIndicator color={defaultTheme.colors.green} /><Text style={styles.subtitle}>Getting things ready…</Text></View>; }
const styles = StyleSheet.create({ card: { backgroundColor: colors.white, borderColor: colors.border, borderWidth: 1, borderRadius: radii.lg, padding: spacing.lg, gap: spacing.sm, ...shadow }, button: { minHeight: 56, borderRadius: radii.md, alignItems: 'center', justifyContent: 'center', paddingHorizontal: spacing.lg, backgroundColor: colors.green }, secondary: { backgroundColor: colors.greenTint }, quiet: { backgroundColor: 'transparent', borderWidth: 1, borderColor: colors.border }, danger: { backgroundColor: colors.coralTint }, pressed: { opacity: 0.8 }, disabled: { opacity: 0.5 }, buttonText: { color: colors.white, fontWeight: '800', fontSize: typography.body }, darkButtonText: { color: colors.greenDark }, heading: { gap: 6 }, title: { color: colors.ink, fontSize: typography.title, fontWeight: '800', letterSpacing: -0.5 }, subtitle: { color: colors.muted, fontSize: typography.bodyLarge, lineHeight: 26 }, pill: { alignSelf: 'flex-start', borderRadius: radii.pill, paddingHorizontal: 12, paddingVertical: 6 }, pillText: { color: colors.greenDark, fontWeight: '800', fontSize: typography.label }, offline: { backgroundColor: colors.greenTint, padding: 12, borderRadius: radii.md }, offlineText: { color: colors.greenDark, fontWeight: '700' }, label: { color: colors.ink, fontSize: typography.body, fontWeight: '800' }, field: { borderWidth: 1, borderColor: colors.border, borderRadius: radii.md, backgroundColor: colors.white, padding: 14, color: colors.ink, fontSize: typography.body }, loading: { flex: 1, alignItems: 'center', justifyContent: 'center', gap: 12 } });
